export const countries = [
  { code: 'AF', name: 'Afghanistan', nameEs: 'Afganistán' },
  { code: 'AL', name: 'Albania', nameEs: 'Albania' },
  { code: 'DZ', name: 'Algeria', nameEs: 'Argelia' },
  { code: 'AD', name: 'Andorra', nameEs: 'Andorra' },
  { code: 'AO', name: 'Angola', nameEs: 'Angola' },
  { code: 'AR', name: 'Argentina', nameEs: 'Argentina' },
  { code: 'AM', name: 'Armenia', nameEs: 'Armenia' },
  { code: 'AU', name: 'Australia', nameEs: 'Australia' },
  { code: 'AT', name: 'Austria', nameEs: 'Austria' },
  { code: 'AZ', name: 'Azerbaijan', nameEs: 'Azerbaiyán' },
  { code: 'BS', name: 'Bahamas', nameEs: 'Bahamas' },
  { code: 'BH', name: 'Bahrain', nameEs: 'Baréin' },
  { code: 'BD', name: 'Bangladesh', nameEs: 'Bangladés' },
  { code: 'BB', name: 'Barbados', nameEs: 'Barbados' },
  { code: 'BY', name: 'Belarus', nameEs: 'Bielorrusia' },
  { code: 'BE', name: 'Belgium', nameEs: 'Bélgica' },
  { code: 'BZ', name: 'Belize', nameEs: 'Belice' },
  { code: 'BJ', name: 'Benin', nameEs: 'Benín' },
  { code: 'BT', name: 'Bhutan', nameEs: 'Bután' },
  { code: 'BO', name: 'Bolivia', nameEs: 'Bolivia' },
  { code: 'BA', name: 'Bosnia and Herzegovina', nameEs: 'Bosnia y Herzegovina' },
  { code: 'BW', name: 'Botswana', nameEs: 'Botsuana' },
  { code: 'BR', name: 'Brazil', nameEs: 'Brasil' },
  { code: 'BN', name: 'Brunei', nameEs: 'Brunéi' },
  { code: 'BG', name: 'Bulgaria', nameEs: 'Bulgaria' },
  { code: 'BF', name: 'Burkina Faso', nameEs: 'Burkina Faso' },
  { code: 'BI', name: 'Burundi', nameEs: 'Burundi' },
  { code: 'KH', name: 'Cambodia', nameEs: 'Camboya' },
  { code: 'CM', name: 'Cameroon', nameEs: 'Camerún' },
  { code: 'CA', name: 'Canada', nameEs: 'Canadá' },
  { code: 'CV', name: 'Cape Verde', nameEs: 'Cabo Verde' },
  { code: 'CF', name: 'Central African Republic', nameEs: 'República Centroafricana' },
  { code: 'TD', name: 'Chad', nameEs: 'Chad' },
  { code: 'CL', name: 'Chile', nameEs: 'Chile' },
  { code: 'CN', name: 'China', nameEs: 'China' },
  { code: 'CO', name: 'Colombia', nameEs: 'Colombia' },
  { code: 'KM', name: 'Comoros', nameEs: 'Comoras' },
  { code: 'CG', name: 'Congo', nameEs: 'Congo' },
  { code: 'CR', name: 'Costa Rica', nameEs: 'Costa Rica' },
  { code: 'HR', name: 'Croatia', nameEs: 'Croacia' },
  { code: 'CU', name: 'Cuba', nameEs: 'Cuba' },
  { code: 'CY', name: 'Cyprus', nameEs: 'Chipre' },
  { code: 'CZ', name: 'Czech Republic', nameEs: 'República Checa' },
  { code: 'DK', name: 'Denmark', nameEs: 'Dinamarca' },
  { code: 'DJ', name: 'Djibouti', nameEs: 'Yibuti' },
  { code: 'DM', name: 'Dominica', nameEs: 'Dominica' },
  { code: 'DO', name: 'Dominican Republic', nameEs: 'República Dominicana' },
  { code: 'EC', name: 'Ecuador', nameEs: 'Ecuador' },
  { code: 'EG', name: 'Egypt', nameEs: 'Egipto' },
  { code: 'SV', name: 'El Salvador', nameEs: 'El Salvador' },
  { code: 'GQ', name: 'Equatorial Guinea', nameEs: 'Guinea Ecuatorial' },
  { code: 'ER', name: 'Eritrea', nameEs: 'Eritrea' },
  { code: 'EE', name: 'Estonia', nameEs: 'Estonia' },
  { code: 'ET', name: 'Ethiopia', nameEs: 'Etiopía' },
  { code: 'FJ', name: 'Fiji', nameEs: 'Fiyi' },
  { code: 'FI', name: 'Finland', nameEs: 'Finlandia' },
  { code: 'FR', name: 'France', nameEs: 'Francia' },
  { code: 'GA', name: 'Gabon', nameEs: 'Gabón' },
  { code: 'GM', name: 'Gambia', nameEs: 'Gambia' },
  { code: 'GE', name: 'Georgia', nameEs: 'Georgia' },
  { code: 'DE', name: 'Germany', nameEs: 'Alemania' },
  { code: 'GH', name: 'Ghana', nameEs: 'Ghana' },
  { code: 'GR', name: 'Greece', nameEs: 'Grecia' },
  { code: 'GD', name: 'Grenada', nameEs: 'Granada' },
  { code: 'GT', name: 'Guatemala', nameEs: 'Guatemala' },
  { code: 'GN', name: 'Guinea', nameEs: 'Guinea' },
  { code: 'GW', name: 'Guinea-Bissau', nameEs: 'Guinea-Bisáu' },
  { code: 'GY', name: 'Guyana', nameEs: 'Guyana' },
  { code: 'HT', name: 'Haiti', nameEs: 'Haití' },
  { code: 'HN', name: 'Honduras', nameEs: 'Honduras' },
  { code: 'HU', name: 'Hungary', nameEs: 'Hungría' },
  { code: 'IS', name: 'Iceland', nameEs: 'Islandia' },
  { code: 'IN', name: 'India', nameEs: 'India' },
  { code: 'ID', name: 'Indonesia', nameEs: 'Indonesia' },
  { code: 'IR', name: 'Iran', nameEs: 'Irán' },
  { code: 'IQ', name: 'Iraq', nameEs: 'Irak' },
  { code: 'IE', name: 'Ireland', nameEs: 'Irlanda' },
  { code: 'IL', name: 'Israel', nameEs: 'Israel' },
  { code: 'IT', name: 'Italy', nameEs: 'Italia' },
  { code: 'JM', name: 'Jamaica', nameEs: 'Jamaica' },
  { code: 'JP', name: 'Japan', nameEs: 'Japón' },
  { code: 'JO', name: 'Jordan', nameEs: 'Jordania' },
  { code: 'KZ', name: 'Kazakhstan', nameEs: 'Kazajistán' },
  { code: 'KE', name: 'Kenya', nameEs: 'Kenia' },
  { code: 'KI', name: 'Kiribati', nameEs: 'Kiribati' },
  { code: 'KW', name: 'Kuwait', nameEs: 'Kuwait' },
  { code: 'KG', name: 'Kyrgyzstan', nameEs: 'Kirguistán' },
  { code: 'LA', name: 'Laos', nameEs: 'Laos' },
  { code: 'LV', name: 'Latvia', nameEs: 'Letonia' },
  { code: 'LB', name: 'Lebanon', nameEs: 'Líbano' },
  { code: 'LS', name: 'Lesotho', nameEs: 'Lesoto' },
  { code: 'LR', name: 'Liberia', nameEs: 'Liberia' },
  { code: 'LY', name: 'Libya', nameEs: 'Libia' },
  { code: 'LI', name: 'Liechtenstein', nameEs: 'Liechtenstein' },
  { code: 'LT', name: 'Lithuania', nameEs: 'Lituania' },
  { code: 'LU', name: 'Luxembourg', nameEs: 'Luxemburgo' },
  { code: 'MG', name: 'Madagascar', nameEs: 'Madagascar' },
  { code: 'MW', name: 'Malawi', nameEs: 'Malaui' },
  { code: 'MY', name: 'Malaysia', nameEs: 'Malasia' },
  { code: 'MV', name: 'Maldives', nameEs: 'Maldivas' },
  { code: 'ML', name: 'Mali', nameEs: 'Malí' },
  { code: 'MT', name: 'Malta', nameEs: 'Malta' },
  { code: 'MH', name: 'Marshall Islands', nameEs: 'Islas Marshall' },
  { code: 'MR', name: 'Mauritania', nameEs: 'Mauritania' },
  { code: 'MU', name: 'Mauritius', nameEs: 'Mauricio' },
  { code: 'MX', name: 'Mexico', nameEs: 'México' },
  { code: 'FM', name: 'Micronesia', nameEs: 'Micronesia' },
  { code: 'MD', name: 'Moldova', nameEs: 'Moldavia' },
  { code: 'MC', name: 'Monaco', nameEs: 'Mónaco' },
  { code: 'MN', name: 'Mongolia', nameEs: 'Mongolia' },
  { code: 'ME', name: 'Montenegro', nameEs: 'Montenegro' },
  { code: 'MA', name: 'Morocco', nameEs: 'Marruecos' },
  { code: 'MZ', name: 'Mozambique', nameEs: 'Mozambique' },
  { code: 'MM', name: 'Myanmar', nameEs: 'Birmania' },
  { code: 'NA', name: 'Namibia', nameEs: 'Namibia' },
  { code: 'NR', name: 'Nauru', nameEs: 'Nauru' },
  { code: 'NP', name: 'Nepal', nameEs: 'Nepal' },
  { code: 'NL', name: 'Netherlands', nameEs: 'Países Bajos' },
  { code: 'NZ', name: 'New Zealand', nameEs: 'Nueva Zelanda' },
  { code: 'NI', name: 'Nicaragua', nameEs: 'Nicaragua' },
  { code: 'NE', name: 'Niger', nameEs: 'Níger' },
  { code: 'NG', name: 'Nigeria', nameEs: 'Nigeria' },
  { code: 'KP', name: 'North Korea', nameEs: 'Corea del Norte' },
  { code: 'MK', name: 'North Macedonia', nameEs: 'Macedonia del Norte' },
  { code: 'NO', name: 'Norway', nameEs: 'Noruega' },
  { code: 'OM', name: 'Oman', nameEs: 'Omán' },
  { code: 'PK', name: 'Pakistan', nameEs: 'Pakistán' },
  { code: 'PW', name: 'Palau', nameEs: 'Palaos' },
  { code: 'PA', name: 'Panama', nameEs: 'Panamá' },
  { code: 'PG', name: 'Papua New Guinea', nameEs: 'Papúa Nueva Guinea' },
  { code: 'PY', name: 'Paraguay', nameEs: 'Paraguay' },
  { code: 'PE', name: 'Peru', nameEs: 'Perú' },
  { code: 'PH', name: 'Philippines', nameEs: 'Filipinas' },
  { code: 'PL', name: 'Poland', nameEs: 'Polonia' },
  { code: 'PT', name: 'Portugal', nameEs: 'Portugal' },
  { code: 'QA', name: 'Qatar', nameEs: 'Catar' },
  { code: 'RO', name: 'Romania', nameEs: 'Rumanía' },
  { code: 'RU', name: 'Russia', nameEs: 'Rusia' },
  { code: 'RW', name: 'Rwanda', nameEs: 'Ruanda' },
  { code: 'KN', name: 'Saint Kitts and Nevis', nameEs: 'San Cristóbal y Nieves' },
  { code: 'LC', name: 'Saint Lucia', nameEs: 'Santa Lucía' },
  { code: 'VC', name: 'Saint Vincent and the Grenadines', nameEs: 'San Vicente y las Granadinas' },
  { code: 'WS', name: 'Samoa', nameEs: 'Samoa' },
  { code: 'SM', name: 'San Marino', nameEs: 'San Marino' },
  { code: 'ST', name: 'Sao Tome and Principe', nameEs: 'Santo Tomé y Príncipe' },
  { code: 'SA', name: 'Saudi Arabia', nameEs: 'Arabia Saudita' },
  { code: 'SN', name: 'Senegal', nameEs: 'Senegal' },
  { code: 'RS', name: 'Serbia', nameEs: 'Serbia' },
  { code: 'SC', name: 'Seychelles', nameEs: 'Seychelles' },
  { code: 'SL', name: 'Sierra Leone', nameEs: 'Sierra Leona' },
  { code: 'SG', name: 'Singapore', nameEs: 'Singapur' },
  { code: 'SK', name: 'Slovakia', nameEs: 'Eslovaquia' },
  { code: 'SI', name: 'Slovenia', nameEs: 'Eslovenia' },
  { code: 'SB', name: 'Solomon Islands', nameEs: 'Islas Salomón' },
  { code: 'SO', name: 'Somalia', nameEs: 'Somalia' },
  { code: 'ZA', name: 'South Africa', nameEs: 'Sudáfrica' },
  { code: 'KR', name: 'South Korea', nameEs: 'Corea del Sur' },
  { code: 'SS', name: 'South Sudan', nameEs: 'Sudán del Sur' },
  { code: 'ES', name: 'Spain', nameEs: 'España' },
  { code: 'LK', name: 'Sri Lanka', nameEs: 'Sri Lanka' },
  { code: 'SD', name: 'Sudan', nameEs: 'Sudán' },
  { code: 'SR', name: 'Suriname', nameEs: 'Surinam' },
  { code: 'SE', name: 'Sweden', nameEs: 'Suecia' },
  { code: 'CH', name: 'Switzerland', nameEs: 'Suiza' },
  { code: 'SY', name: 'Syria', nameEs: 'Siria' },
  { code: 'TW', name: 'Taiwan', nameEs: 'Taiwán' },
  { code: 'TJ', name: 'Tajikistan', nameEs: 'Tayikistán' },
  { code: 'TZ', name: 'Tanzania', nameEs: 'Tanzania' },
  { code: 'TH', name: 'Thailand', nameEs: 'Tailandia' },
  { code: 'TL', name: 'Timor-Leste', nameEs: 'Timor Oriental' },
  { code: 'TG', name: 'Togo', nameEs: 'Togo' },
  { code: 'TO', name: 'Tonga', nameEs: 'Tonga' },
  { code: 'TT', name: 'Trinidad and Tobago', nameEs: 'Trinidad y Tobago' },
  { code: 'TN', name: 'Tunisia', nameEs: 'Túnez' },
  { code: 'TR', name: 'Turkey', nameEs: 'Turquía' },
  { code: 'TM', name: 'Turkmenistan', nameEs: 'Turkmenistán' },
  { code: 'TV', name: 'Tuvalu', nameEs: 'Tuvalu' },
  { code: 'UG', name: 'Uganda', nameEs: 'Uganda' },
  { code: 'UA', name: 'Ukraine', nameEs: 'Ucrania' },
  { code: 'AE', name: 'United Arab Emirates', nameEs: 'Emiratos Árabes Unidos' },
  { code: 'GB', name: 'United Kingdom', nameEs: 'Reino Unido' },
  { code: 'US', name: 'United States', nameEs: 'Estados Unidos' },
  { code: 'UY', name: 'Uruguay', nameEs: 'Uruguay' },
  { code: 'UZ', name: 'Uzbekistan', nameEs: 'Uzbekistán' },
  { code: 'VU', name: 'Vanuatu', nameEs: 'Vanuatu' },
  { code: 'VA', name: 'Vatican City', nameEs: 'Ciudad del Vaticano' },
  { code: 'VE', name: 'Venezuela', nameEs: 'Venezuela' },
  { code: 'VN', name: 'Vietnam', nameEs: 'Vietnam' },
  { code: 'YE', name: 'Yemen', nameEs: 'Yemen' },
  { code: 'ZM', name: 'Zambia', nameEs: 'Zambia' },
  { code: 'ZW', name: 'Zimbabwe', nameEs: 'Zimbabue' },
];
